name: 빈 좌석 체크

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:

jobs:
  check_empty_seat:
    runs-on: ubuntu-latest

    steps:
      - name: 빈 좌석 확인
        uses: actions/github-script@v6
        with:
          script: |
            // 공연/블록 정보
            const productId = '211782';
            const scheduleNo = '100003';
            const zid = '180';

            // 좌석 상태 API 요청
            const response = await fetch(`https://ticket.melon.com/seats?productId=${productId}&scheduleNo=${scheduleNo}`);
            const data = await response.json();
            const seats = data.seats;

            // 빈 좌석 확인
            const emptySeats = seats.filter(seat => seat.zid == zid && seat.status === 'available');

            if (emptySeats.length > 0) {
              console.log(`빈 좌석 있음: ${emptySeats.length}개`);
              const webhookUrl = process.env.SLACK_WEBHOOK_URL;
              await fetch(webhookUrl, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  text: `블록 ${zid}에 빈 좌석 ${emptySeats.length}개 있음! 예매하러 가세요!`
                })
              });
            } else {
              console.log(`블록 ${zid}에 빈 좌석 없음`);
            }
